### ISSUE TITLE
Choose a license for the source files

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/SURFER-Galleries#11]
Once we made a decision about the license of the source files, we have to ask each author to agree to this new license.

**Comment by jgmbenoit** [comment]
For packaging, a licence is definitely needed.

**Comment by porst17** [comment]
@andreasdanielmatt I cannot move forward alone here. We have to discuss this due to the dependencies on the other authors.

**Comment by porst17** [comment]
@jgmbenoit Do you have any recommendation for an appropriate license? I was thinking of some Creative Commons license. Not sure if this is the right thing for the LaTeX source code.

**Comment by jgmbenoit** [comment]
I am not an expert in (human) law. Having said that, the package surfer-alggeo-galleries assumes a CC-BY-SA-4.0 ( Creative Commons Attribution-ShareAlike 4.0 International ) which meets the DFSG ( https://wiki.debian.org/DFSGLicenses ), as such the package can be distributed in main. For my own academic/scientific documents (posters + seminar slides in PDF) I choose the Creative Commons Attribution 4.0 International License before to upload them to ResearchGate. Concerning the LaTeX source code, I guess that the content must be separated from the container (as usual with [La]TeX): my understanding is that the content is subject to the same license as the final PDF; the container (the CLS file) might be subject to the LaTeX Project Public License (LPPL).
On the other hand, I suppose that the IMAGINARY.org material (web + exposition) is somehow already protected: consistency and harmonization is certainly the best guidance here.

**Comment by porst17** [comment]
I also think that CC BY-SA 4.0 is appropriate. I did not consider using the LPPL for the .cls file, but maybe, this is an option. Let's wait until the license for the content files has been chosen. I will apply all the licenses at once then.
