### ISSUE TITLE
Choose a license for the compiled gallery files

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/SURFER-Galleries#12]
I suggest CC BY-SA (NC?).

Once we made a decision about the license of the PDF files, we have to ask each author to agree to this new license. Maybe there is also a dependency on the license for the source files

**Comment by jgmbenoit** [comment]
For packaging, a licence is definitely needed.

**Comment by porst17** [comment]
@andreasdanielmatt This is still open and has to be discussed and finalized. Otherwise, packaging as part of Debian, Ubuntu etc. will hardly be possible.

**Comment by jgmbenoit** [comment]
``Otherwise, packaging as part of Debian, Ubuntu etc. will hardly be possible.'' Why ? For License reasons or for technical reasons ?

**Comment by porst17** [comment]
License reasons, as you pointed out above:
> For packaging, a licence is definitely needed.

**Comment by jgmbenoit** [comment]
Ok. So now it is possible to package it modulo technical issues (if any).
