### ISSUE TITLE
[normal, packaging] quid MessagesBundle_TLC.properties and Impressum_TLC.png files ?

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/SURFER-Galleries#27]
I think that it would be more rational to place the MessagesBundle_TLC.properties and Impressum_TLC.png files with the Galleries material.

**Comment by jgmbenoit** [comment]
The Impressum.png must certainly stay with Surfer-java.

**Comment by jgmbenoit** [comment]
The Impressum_{en,de,nl}.png are distributed within the surfer-alggeo-java deb ball (read: not within the surfer-alggeo-galleries deb balls.

**Comment by jgmbenoit** [comment]
Concerning the MessagesBundle_TLC.properties data files: I am wondering if the few info they contains could be encapsulated in the PDF file. The rational is that we can then only deal with the PDF files (which BTW can be viewed with any regular pdfviewer)

**Comment by jgmbenoit** [comment]
I am definitively think that the MessagesBundle_TLC.properties keywords list must be encoded in the PDF files, in practice in the SurferDesc.cls LaTeX CLaSs file.

**Comment by porst17** [comment]
The `MessageBundle_TLC.properties` files contain the localization strings for various labels in the SURFER program. It is entirely independent of the galleries. These labels have no relation to the PDF files of the galleries.

A different story is that both, the `MessageBundle_TLC.properties` and the galleries, are needed for full localization of SURFER to another language. But the `.properties` file still doesn't contain any information relevant for the galleries or vice versa.

I don't see a point of putting the property files into the gallery repository nor does it make any sense to make them available in the LaTeX class file.

**Comment by porst17** [comment]
I will close this and think of where to put the `MessageBundle_TLC.properties` files in the SURFER project (see IMAGINARY/SURFER#14). It's clearly not a good idea to just keep them inside the jar blobs.

**Comment by jgmbenoit** [comment]
My issue was mainly: what does happens if a gallery material in a foreign language not yet supported in the viewer is added ?

**Comment by porst17** [comment]
Nothing happens. The viewer looks for all the languages that have a `MessageBundle_TLC.properties` file. Only if the program itself is supporting the language (via the message bundle), the PDF will be loaded. Otherwise it will be ignored.

**Comment by jgmbenoit** [comment]
Have you already wiped out the gallery material from the SURFER source ?

**Comment by porst17** [comment]
No. I was working on jsurf first, then the galleries and tomorrow I plan to work on Surfer itself.

**Comment by jgmbenoit** [comment]
I think this is a part of the wipe out, so let come back to this mater later to see clearer.
