### ISSUE TITLE
[important] changelog + version

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/SURFER-Galleries#29]
Please provide a changelog and a version string (or something)
The underlying/implicit rational is to clear separate the java source material from the galleries' material:
a GNUmakefile that, besides  parallel composition of LaTeX material,  provides lingual and common data Java ARchives build _and_ dispatch (and clean).

**Comment by porst17** [comment]
The version is implicit via git tags and the change log. I hope, this is good is enough. I want to avoid having a separate version file I would need to keep consistent with the change log and the most recent tag all the time.

**Comment by jgmbenoit** [comment]
git tags are for git developers, and git may be replaced soonner or later: git tag is not perenne.
Final users does not necessary have access to the ChangeLog.
To keep consistency, you can use a GNUmakefile that you do not dispatch and that call the effectively dispatched makefile (if applicable): this an old trick. You may put an authoritative version string/tuple in the LaTeX style file and eventually put it in the PDF meta data (via hypertext). This is really good practise. If someone report an issue in a PDF file, how can we get the involved version ?

**Comment by porst17** [comment]
Can you provide a basic example for this? The makefile(s) and what I have to put in the (Xe)LaTeX sources?

**Comment by jgmbenoit** [comment]
OK. By tomorrow morning, is that ok ?

**Comment by porst17** [comment]
That's fine.

**Comment by jgmbenoit** [comment]
Concerning the make material, a good but rather advanced example is provided within the gnulib material: on Debain based box: /usr/share/gnulib , the top folder contains the example. I will send by example a simpler example of mine.

**Comment by porst17** [comment]
I added the version string to the class file but I still don't see the connection between the change log, the version string and the makefile. If you want me to provide a makefile for building all the PDFs, please open another issue. Also, I am not very good a writing makefiles since I am typically using higher level build tools.

**Comment by jgmbenoit** [comment]
Ok, I will pull a request with a Makefile and a GNUmakefile by the week-end.
In fact, a Makefile is use to make the Debian package. I will adopt it.

**Comment by jgmbenoit** [comment]
See PR #34  #33 (and the old #30)
